package main

import (
	"bufio"
	"encoding/base64"
	"fmt"
	"io/ioutil"
	"os"
)

func main() {
	// Open file on disk.
	f, err := os.Open("favicon.ico")
	if err != nil {
		fmt.Println(err)
	}

	var src []byte

	// Read entire icon into byte slice.
	src, err = ioutil.ReadAll(bufio.NewReader(f))
	if err != nil {
		fmt.Println(err)
	}

	src = []byte(fmt.Sprintf(
		"// DO NOT EDIT! This file is generated by `go run /cmd/base64.go`\n// Please edit favicon.ico & then rebuild Triumph Challenge.\npackage main\n\nconst favicon = \"%s\"\n",
		base64.StdEncoding.EncodeToString(src),
	))

	err = ioutil.WriteFile("favicon.go", src, 0600)
	if err != nil {
		fmt.Println(err)
	}
}
